export const APP_ROUTES = {
  root: '/',
  login: '/admin/login',
  adminDashboard: '/admin/dashboard',
  adminMiPerfil: '/admin/mi-perfil',
  adminCarreras: '/admin/carreras',
  adminUnidadesCurriculares: '/admin/unidades-curriculares',
  adminCiclosLectivos: '/admin/ciclos-lectivos',
  adminEstudiantes: '/admin/estudiantes',
  adminPreinscriptos: '/admin/preinscriptos',
  adminDocentes: '/admin/docentes',
  adminAdministrativos: '/admin/administrativos',
  adminTurnos: '/admin/turnos-examen',
  adminMesas: '/admin/mesas-examen',
  adminCooperadora: '/admin/cooperadora',
  adminMabs: '/admin/mabs',
  adminPlanEstudios: '/admin/plan-estudios',
  adminLogoutSuccess: '/admin/logout-success',
  adminRecuperarContrasena: '/admin/recuperar-contrasenia',
  adminRestablecerContrasena: '/admin/restablecer-contrasenia/:token',
  adminRestablecerExitoso: '/admin/restablecer-exitoso',
} as const;
